name: Use the Composite Action with Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: workToBeDone/demo@main
        with:
          who-to-greet: 'Mona the Octocat'
